### ISSUE TITLE
Add .gitignore file and remove binary files from the git repo

### ISSUE THREAD

**Issue by JWBlash** [DanBlash/Learning-C#5]
The convention in git repositories is for the repository to _only_ include the source files, and expect that those who want to use the software build it themselves (or download it from somewhere else you've deployed the built artifacts to). This way you're not bloating the repo with a bunch of potentially huge binaries, which will increase the amount of time it takes to perform git operations as the project grows (amongst other reasons)

So add a `.gitignore` file at the top of the repo, whose contents calls out each of the obj files you'll end up creating from your C files. At the time of writing this, it would look something like the following:
```
Anagram Finder
Snake_Game
hello world
```

**Comment by JWBlash** [comment]
If this seems done to you @DanBlash, you can go ahead and close this guy

**Comment by DanBlash** [comment]
Closed
